######################################################################
# Author: Dr. Scott Heggen        TODO: Change this to your names
# Username: heggens               TODO: Change this to your usernames
#
# Assignment: T11: The Legend of Tuna: Breath of Catnip
#
# Purpose: Learn about classes, inheritance, and Pygame
######################################################################
# Acknowledgements:
#
# Inspired by Zelda, rebuilt into Python by: https://github.com/clear-code-projects/Zelda
# Art generated by Stable Diffusion: https://stablediffusionweb.com/app/image-generator
# Borrowed some ideas from: https://realpython.com/pygame-a-primer/

# licensed under a Creative Commons
# Attribution-Noncommercial-Share Alike 3.0 United States License.
####################################################################################
import pygame, random
import random


class Fruits(pygame.sprite.Sprite):
    move_distance = 10
    directions = ["south"]

    def __init__(self, screen_size):
        """
        Represents the falling red apple in the game.

        :param screen_size: size of the window, for ensuring the NPC stays on screen
        """
        print("Spawning Apple")
        self.screen_size = screen_size
        super().__init__()
        self.surf = pygame.image.load('images/apple.png')
        self.surf = pygame.transform.scale(self.surf, (25, 25))
        self.surf.set_colorkey((255, 255, 255), pygame.RLEACCEL)
        self.rect = self.surf.get_rect()
        self.rect.move_ip(self.screen_size[0]//4, self.screen_size[1]//4)
        self.path = random.choice(self.directions)
        self.position = [50, 50]

    def get_direction(self):
        """
        Makes the apple fall

        :return: None
        """
        if self.rect.bottom >= self.screen_size[1]:
            self.path = "south"


    def movement(self):
        """
        Moves the NPC around.

        :return: None
        """

        if self.path == "south":
            self.rect.move_ip(0, self.move_distance)
            self.position[1] += self.move_distance

        self.get_direction()




